resolver: lts-9.21
compiler: ghcjs-0.2.1.9009021_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9009021_ghc-8.0.2:
           url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9009021.tar.gz
           sha1: b1740c3c99e5039ac306702894cd6e58283f4d31

allow-newer: true

packages:
- '.'
- '../common'

- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: 2c089a255184ac1ae8250be44dcb44fddad7ddd5
  extra-dep: true

- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: 8bde2d72193369c92a995820ca1f56690d3c8ec3
  subdirs:
  - reflex-dom-core
  - reflex-dom
  extra-dep: true

- location:
    git: https://github.com/reflex-frp/reflex-dom-contrib
    commit: 3efa8e4fa35161ea967252106ef7177a8360485b
  extra-dep: true

- location:
    git: https://github.com/TidalCycles/Tidal.git
    commit: 65724857fad9983b35dd24fe37fb36a0cb7dbbb8
  extra-dep: true

- location:
    git: https://github.com/dktr0/MusicW.git
    commit: d7d4c57a54f47eb60144dbd36e16009ae5d73925
  extra-dep: true

- location:
    git: https://github.com/dktr0/Punctual.git
    commit: 37968562ff7d85082ff4a38e6871b552b228cb56
  extra-dep: true

extra-deps:
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - ghcjs-dom-0.9.2.0
  - ghcjs-dom-jsffi-0.9.2.0
  - dependent-sum-template-0.0.0.6
  - jsaddle-0.9.5.0
  - zenc-0.1.1
  - monoidal-containers-0.4.0.0
  - hosc-0.16
  - parsec-numbers-0.1.0

  # hspec and hspec-2.2.4 dependencies. Newer version may or may not work in GHCJS
  - hspec-2.2.4
  - hspec-core-2.2.4
  - hspec-expectations-0.7.2
  - hspec-discover-2.2.4
  - HUnit-1.3.1.2
  - QuickCheck-2.8.2
  - quickcheck-io-0.1.4
